export const Dapps = [
    {
        name: 'PancakeSwap',
        url: 'https://pancakeswap.finance/',
        description: 'Most popular and feature-rich DeFi DApp and AMM',
        trusted: '',
        img: 'https://__url__PancakeSwap.png',
        category: 'DEFI',
    },
    {
        name: 'Enchanter Finance',
        url: 'https://app.enchanter.fi/',
        description: 'The 1st Social Trading AMM DEX',
        trusted: '',
        img: 'https://__url__EnchanterLogo.png',
        category: 'DEX',
    },
    {
        name: 'ItsRare Marketplace',
        url: 'https://aptos.itsrare.app/',
        description: 'A Gateway for creating, discovering and trading digital asset on the Aptos Blockchain',
        trusted: '',
        img: 'https://__url__Itrare.png',
        category: 'MARKETPLACE',
    },
    {
        name: 'Kana Labs',
        url: 'https://www.kanalabs.io/',
        description: 'DeFi platform where users across multiple blockchains',
        trusted: '',
        img: 'https://__url__Kana.png',
        category: 'DEFI',
    },
    {
        name: 'Proton Sale',
        url: 'https://protonsale.io/',
        description: 'The launchpad Protocol',
        trusted: '',
        img: 'https://__url__ProtonSale.jpeg',
        category: 'LAUNCHPAD',
    },
    {
        name: 'Souffl3',
        url: 'https://souffl3.com/',
        description: 'Smart Trading NFT Marketplace',
        trusted: '',
        img: 'https://__url__Souffl3.png',
        category: 'MARKETPLACE',
    },
    {
        name: 'Aptoswap',
        url: 'https://aptoswap.net/',
        description: 'Lighweight & Powerful Swap Platform',
        trusted: '',
        img: 'https://__url__AptosSwap.png',
        category: 'LENDING',
    },
    {
        name: 'Topaz',
        url: 'https://www.topaz.so/',
        description: 'A Powerful, Safety, and Scalable NFT Marketplace on Aptos',
        trusted: '',
        img: 'https://__url__Topaz.svg',
        category: 'MARKETPLACE',
    },
    {
        name: 'Seam Money',
        url: 'https://www.seam.money/',
        description: 'Structured DeFi Products',
        trusted: '',
        img: 'https://__url__Seam.png',
        category: 'OTHER',
    },
    {
        name: 'Econia',
        url: 'https://www.econia.dev/',
        description: 'Hyper-parallelized on-chain CLOB for the Aptos blockchain',
        trusted: '',
        img: 'https://__url__Econia.png',
        category: 'OTHER',
    },
    {
        name: 'Tortuga Finance',
        url: 'https://dev.app.tortuga.finance/',
        description: 'Tortuga Finance is the most trusted liquid staking protocol on Aptos',
        trusted: '',
        img: 'https://__url__Tortuga.png',
        category: 'STAKING',
    },
    {
        name: 'Aries Markets',
        url: 'https://ariesmarkets.xyz/',
        description:
            'Aries Market is a decentralised margin trading protocol on Aptos. Lend, borrow and trade with margin via a fully on-chain order book',
        trusted: '',
        img: 'https://__url__AriesMarket.png',
        category: 'LENDING',
    },
    {
        name: 'Tsunami',
        url: 'https://tsunami.finance/',
        description: 'Trade spot & perpetuals with 0% slippage.',
        trusted: '',
        img: 'https://__url__Tsunami.png',
        category: 'DEFI',
    },
    {
        name: 'Mojito',
        url: 'https://www.mojito.markets/',
        description: 'Decentralised Prediction Markets on the blockchain',
        trusted: '',
        img: 'https://__url__Mojito.jpeg',
        category: 'OTHER',
    },
    {
        name: 'Momentum Safe',
        url: 'https://app.m-safe.io/',
        description: 'Multi-signature wallet solution The most secure digital assets management and analytics tool on Move',
        trusted: '',
        img: 'https://__url__Momentum.png',
        category: 'OTHER',
    },
    {
        name: 'Celer cBridge',
        url: 'https://cbridge.celer.network/1/12360001/USDC',
        description: 'cBridge introduces the best-in-class cross-chain token bridging experience with deep liquidity for users',
        trusted: '',
        img: 'https://__url__Celer.png',
        category: 'DEFI',
    },
    {
        name: 'Abel finance',
        url: 'https://abelfinance.xyz/#/markets',
        description: 'The first fully decentralized multiple cross-chain lending Defi running on the APTOS network',
        trusted: '',
        img: 'https://__url__Abel.jpeg',
        category: 'LENDING',
    },
    {
        name: 'Meerio',
        url: 'https://meeiro.xyz/',
        description: 'A user driven IDO launchpad on Aptos Network connecting retail investors and projects together.',
        trusted: '',
        img: 'https://__url__Meerio.svg',
        category: 'LAUNCHPAD',
    },
    {
        name: 'Meson.fi',
        url: 'https://meson.fi/fewcha',
        description: 'Meson provides minute-fast swaps with almost-zero fee & slippage across all major blockchains.',
        trusted: '',
        img: 'https://__url__Meson.png',
        category: 'LENDING',
    },
    {
        name: 'Aptin',
        url: 'https://app.aptin.io/',
        description:
            'Aptin is a decentralised non-custodial liquidity market protocol where users can participate as depositors or borrowers',
        trusted: '',
        img: 'https://__url__Aptin.png',
        category: 'LENDING',
    },
]
